kind: pipeline
name: default

steps:
- name: test
  image: python
  environment:
    TEST_ENV_PLAIN: Testing the environment variables.
    TEST_ENV_ENC:
      from_secret: test
  commands:
  - pip install -r requirements.txt
  - python test.py

---
kind: secret
data:
  test: Vij5eGL77bY6SsLiGhB_FeH0xxFiGTKXx2NRr9KjLZ5DWRldzzcEtSxNmB1_yZcctVY=
