kind: pipeline
name: default

steps:
- name: cf-deploy
  image: governmentpaas/cf-cli
  environment:
    GPAAS_APP_NAME: paas-drone-hello-world
    GPAAS_USER:
      from_secret: gpaas_user
    GPAAS_PASS:
      from_secret: gpaas_pass
    GPAAS_ORG: gds-tech-ops
    GPAAS_SPACE: sandbox
    GPAAS_API: api.cloud.service.gov.uk
  commands:
    # set api endpoint and login
    - cf login -a $GPAAS_API -u $GPAAS_USER -p "$GPAAS_PASS"
    # set the target
    - cf target -o $GPAAS_ORG -s $GPAAS_SPACE
    # push the apps
    - cd /drone/src/app
    - cf push $GPAAS_APP_NAME

---
kind: secret
data:
  gpaas_user: 8t16mUfwrLKoqcotYn-nL3N5bkf1AYo-GZcBXVG-Ga_5XGooTHAioh5L-CZ4TDDP5v2_IsmMR75w-2cvNKhZgyusdclZ49cW7BWT9y6bK1_j
  gpaas_pass: DhnL2Vy282jE9f-DdI6tDE6tkilgmC3YapMdI2Rkm8qTUD-PI6QT13QZA2wYMVC2Sa0NISV7ggYyJzK_gEfG
